try{


    console.log(x); // ReferenceError 
    console.log("Working");


}
catch{
    // email to developer
    // log error
    console.log("server is under maintenance");

}
finally{
    console.log("inside finally block")
}